openapi: 3.0.1
info:
  title: AccountsAPI
  description: API Definition of AccountsAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/accounts
paths:
  /all:
    get:
      responses:
        default:
          description: Default response
  /currentaccounts:
    get:
      responses:
        default:
          description: Default response
  /savingsaccounts:
    get:
      responses:
        default:
          description: Default response
  /jointaccounts:
    get:
      responses:
        default:
          description: Default response
  /fixeddeposits:
    get:
      responses:
        default:
          description: Default response
  /update:
    put:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /register:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
