openapi: 3.0.1
info:
  title: LoanAPI
  description: API Definition of LoanAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/loans
paths:
  /types:
    get:
      responses:
        default:
          description: Default response
  /register:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /{loan_id}:
    get:
      parameters:
      - name: loan_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /approve/{loan_id}:
    post:
      parameters:
      - name: loan_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
